name: "[ct-website] Build, Release, Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "preview"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
  DEVL_URL: "http://dev.conntectingthreads.co.uk/"
  PROD_URL: "https://connectingthreads.co.uk/"

jobs:
  hugo-build-release-deploy:
    uses: chnm/.github/.github/workflows/hugo--build-release-deploy.yml@main
    secrets: inherit
    with:
      container-registry: "ghcr.io"
      container-image-name: "ct-website"
      hugo-context-root: "."
      hugo-devl-url: "https://dev.connectingthreads.co.uk"
      hugo-prod-url: "https://connectingthreads.co.uk"
      
      build-artifact-name: "ct-website"
      release-tag-name-type: "iso"
      
      website-devl-fqdn: "dev.connectingthreads.co.uk"
      website-prod-fqdn: "connectingthreads.co.uk"
